name: canada two the revenge
favicon: null
layout_spectrum: 0.26671
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e00227'
    - '#000000'
    - '#8f8f8f'
    - '#4e4e4e'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
