name: canada two the revenge
favicon: null
layout_spectrum: 0.8888428946956992
typography_spectrum: 0.9883579993620515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcff70'
    - '#0796a4'
    - '#f53230'
    - '#715f37'
    - '#011419'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
